package ap

import (
	"fmt"
	"strings"
)

// RenderConfig generates a hostapd configuration file.
//
// The important lines are the three that make hostapd relay EAP rather than terminate it:
//
//	ieee8021x=1                 enable 802.1X
//	wpa_key_mgmt=WPA-EAP        negotiate enterprise key management
//	auth_server_addr=127.0.0.1  send every EAP message to WARP's RADIUS server
//
// With those set, hostapd does beaconing, association and EAPOL, and forwards the EAP
// conversation untouched. That is what makes a patched hostapd-wpe unnecessary: none of the
// interesting logic runs here.
//
// Golden-file tested, because a silently wrong directive produces an access point that comes
// up, beacons correctly, and never forwards a single EAP message.
func RenderConfig(cfg Config) (string, error) {
	if cfg.Interface == "" {
		return "", fmt.Errorf("ap: config needs an interface")
	}
	if cfg.ESSID == "" {
		return "", fmt.Errorf("ap: config needs an ESSID")
	}
	if len(cfg.ESSID) > 32 {
		return "", fmt.Errorf("ap: ESSID is %d octets, maximum is 32", len(cfg.ESSID))
	}
	if cfg.Channel <= 0 {
		return "", fmt.Errorf("ap: config needs a channel")
	}
	if cfg.RADIUSSecret == "" {
		return "", fmt.Errorf("ap: config needs the RADIUS shared secret")
	}
	// A newline in any of these would let a value inject an unrelated directive.
	for name, v := range map[string]string{
		"essid": cfg.ESSID, "interface": cfg.Interface,
		"radius secret": cfg.RADIUSSecret, "bssid": cfg.BSSID,
		"country": cfg.CountryCode,
	} {
		if strings.ContainsAny(v, "\r\n") {
			return "", fmt.Errorf("ap: %s contains a newline", name)
		}
	}

	// The shared secret gets stricter treatment than the newline check above: hostapd reads it
	// to the end of the config line and uses it verbatim as the HMAC key, so a null truncates it
	// (C string), and a space or a control byte is stripped or mangled differently than the
	// server keeps it - either way hostapd and the server end up keyed differently and every
	// Message-Authenticator fails silently. Require printable, non-whitespace ASCII; the daemon
	// generates a hex secret, which satisfies this.
	for _, b := range []byte(cfg.RADIUSSecret) {
		if b <= 0x20 || b >= 0x7f {
			return "", fmt.Errorf("ap: RADIUS secret has a non-printable byte (0x%02x); it must "+
				"be printable ASCII so hostapd keys the same secret the server does", b)
		}
	}

	hwMode := cfg.HWMode
	if hwMode == "" {
		// Channels above 14 are 5 GHz; everything else is 2.4.
		hwMode = "g"
		if cfg.Channel > 14 {
			hwMode = "a"
		}
	}

	radiusAddr := cfg.RADIUSAddr
	if radiusAddr == "" {
		radiusAddr = "127.0.0.1"
	}
	radiusPort := cfg.RADIUSPort
	if radiusPort == 0 {
		radiusPort = 1812
	}

	var b strings.Builder

	b.WriteString("# Generated by WARP. Do not edit: regenerated on every rogue AP start.\n")
	b.WriteString("#\n")
	b.WriteString("# Stock hostapd with an external RADIUS backend. All EAP logic - certificate\n")
	b.WriteString("# presentation, method negotiation, credential capture - lives in WARP's own\n")
	b.WriteString("# RADIUS server, so no patched hostapd-wpe is needed.\n\n")

	fmt.Fprintf(&b, "interface=%s\n", cfg.Interface)
	fmt.Fprintf(&b, "ssid=%s\n", cfg.ESSID)
	fmt.Fprintf(&b, "channel=%d\n", cfg.Channel)
	fmt.Fprintf(&b, "hw_mode=%s\n", hwMode)
	if cfg.BSSID != "" {
		fmt.Fprintf(&b, "bssid=%s\n", cfg.BSSID)
	}
	if cfg.CountryCode != "" {
		fmt.Fprintf(&b, "country_code=%s\n", cfg.CountryCode)
		b.WriteString("ieee80211d=1\n")
	}

	b.WriteString("\n# WPA2-Enterprise.\n")
	b.WriteString("wpa=2\n")
	b.WriteString("wpa_key_mgmt=WPA-EAP\n")
	b.WriteString("wpa_pairwise=CCMP\n")
	b.WriteString("rsn_pairwise=CCMP\n")

	b.WriteString("\n# 802.1X relayed to WARP's RADIUS server. These three lines are the whole\n")
	b.WriteString("# reason a patched hostapd is unnecessary.\n")
	b.WriteString("ieee8021x=1\n")
	b.WriteString("eapol_version=2\n")
	fmt.Fprintf(&b, "auth_server_addr=%s\n", radiusAddr)
	fmt.Fprintf(&b, "auth_server_port=%d\n", radiusPort)
	fmt.Fprintf(&b, "auth_server_shared_secret=%s\n", cfg.RADIUSSecret)
	fmt.Fprintf(&b, "own_ip_addr=%s\n", radiusAddr)
	// NAS identification appears in the RADIUS request, which is what ties a captured
	// credential back to this access point in the report.
	fmt.Fprintf(&b, "nas_identifier=warp-%s\n", sanitiseNAS(cfg.ESSID))

	b.WriteString("\n# Operational.\n")
	b.WriteString("logger_stdout=-1\n")
	b.WriteString("logger_stdout_level=2\n")
	b.WriteString("ctrl_interface=/var/run/hostapd-warp\n")
	b.WriteString("ctrl_interface_group=0\n")
	// Broadcasting the SSID is the point: a client looking for this network must see it.
	b.WriteString("ignore_broadcast_ssid=0\n")
	b.WriteString("macaddr_acl=0\n")
	b.WriteString("auth_algs=1\n")

	return b.String(), nil
}

// sanitiseNAS reduces an ESSID to a NAS identifier.
func sanitiseNAS(s string) string {
	out := make([]rune, 0, len(s))
	for _, r := range s {
		switch {
		case r >= 'a' && r <= 'z', r >= '0' && r <= '9', r == '-':
			out = append(out, r)
		case r >= 'A' && r <= 'Z':
			out = append(out, r+('a'-'A'))
		case r == ' ' || r == '_' || r == '.':
			out = append(out, '-')
		}
	}
	if len(out) == 0 {
		return "ap"
	}
	if len(out) > 24 {
		out = out[:24]
	}
	return string(out)
}
